# Generated by Django 4.2.5 on 2023-09-09 16:57

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_category_avatar_alter_server_members"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="avatar",
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(
                default="avatar.svg", null=True, upload_to=server.models.category_icon_path
            ),
        ),
    ]
