# Generated by Django 4.2.5 on 2023-09-09 17:47

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_remove_category_avatar_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.server_banner_path
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.server_icon_path
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True, null=True, upload_to=server.models.category_icon_path
            ),
        ),
    ]
